name: Automatic Script Execution

on:
  schedule:
    - cron: '20 10 * * *'  # 매일 자정에 실행

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Execute Automation Script
        run: |
          python automation_script.py > output.txt

      - name: Read Output and Create GitHub Issue
        run: |
          result_text=$(cat output.txt)
          python create_issue_script.py

      - name: Cleanup
        run: |
          rm output.txt
